name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: "true"
          allowUpdates: "true"
          bodyFile: "body.md"
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
